- type: pointOfInterest
  id: BasePOI
  abstract: true
  minimumDistance: 2500 # Some sane defaults
  maximumDistance: 5000
  spawnGamePreset: [ NFAdventure, NFPirate ]
  spawnGroup: Optional
  addComponents:
  - type: IFF
    color: "#ffa600"
    readOnly: true
  # Prevent gravity changes
  - type: ForceAnchor
